language: cpp
compiler: gcc
dist: bionic

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # GraphViz
  - sudo apt-get install -qq graphviz

script: 
  - qmake
  - make
  - ./boost_graph_example_6
